Merge rvc2_vertical_stereo and develop

diff --git a/.github/workflows/main.workflow.yml b/.github/workflows/main.workflow.yml
--- a/.github/workflows/main.workflow.yml
+++ b/.github/workflows/main.workflow.yml
@@ -6,21 +6,47 @@ on:
     branches:
       - main
       - develop
-      - gen2
-      - gen2_develop
     tags:
       - 'v*'
   pull_request:
     branches:
       - main
       - develop
-      - gen2
-      - gen2_develop
+    types: [opened, synchronize, reopened, labeled]
 
 jobs:
 
+  # The precheck job determines whether a workflow should be run in full
+  precheck:
+    runs-on: ubuntu-latest
+    outputs:
+      should_run: ${{ steps.check.outputs.should_run }}
+    steps:
+    - name: Evaluate trigger condition
+      id: check
+      run: |
+        EVENT_NAME="${{ github.event_name }}"
+
+        RAW_LABELS='${{ toJson(github.event.pull_request.labels) }}'
+        if [[ "$RAW_LABELS" == "null" || -z "$RAW_LABELS" ]]; then
+          LABELS="[]"
+        else
+          LABELS="$RAW_LABELS"
+        fi
+
+        SHOULD_RUN="true"
+        if [[ "$EVENT_NAME" == "pull_request" ]]; then
+          if ! echo "$LABELS" | jq -r '.[].name' | grep -q "testable"; then
+            SHOULD_RUN="false"
+          fi
+        fi
+
+        echo "should_run=$SHOULD_RUN" >> "$GITHUB_OUTPUT"
+
   style:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
+    needs: [precheck]
+    if: needs.precheck.outputs.should_run == 'true'
 
     steps:
     - uses: actions/checkout@v4
@@ -29,17 +55,20 @@ jobs:
 
     - name: Install format dependencies
       run: |
-        sudo apt-get install clang-format-10
+        sudo apt-get update
+        sudo apt-get install clang-format-18 libopencv-dev libudev-dev
 
     - name: configure
-      run: cmake . -Bbuild -DDEPTHAI_CLANG_FORMAT=ON -DCLANG_FORMAT_BIN=clang-format-10
+      run: cmake . -Bbuild -DDEPTHAI_CLANG_FORMAT=ON -DCLANG_FORMAT_BIN=/usr/bin/clang-format-18
 
     - name: check style
       run: ci/check_format.sh build
 
 
   tidy:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
+    needs: [precheck]
+    if: needs.precheck.outputs.should_run == 'true'
 
     steps:
     - uses: actions/checkout@v4
@@ -49,41 +78,24 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install clang-tidy-10
+        sudo apt-get install clang-tidy-18 libopencv-dev libudev-dev
 
     - name: configure
-      run: cmake . -Bbuild -DDEPTHAI_CLANG_TIDY=ON -DCLANG_TIDY_BIN=clang-tidy-10
+      run: cmake . -Bbuild -DDEPTHAI_CLANG_TIDY=ON -DCLANG_TIDY_BIN=/usr/bin/clang-tidy-18
 
     - name: Run clang-tidy
       run: cmake --build build --parallel 4
 
-
   build:
     runs-on: ${{ matrix.os }}
+    needs: [precheck]
+    if: needs.precheck.outputs.should_run == 'true'
     strategy:
       matrix:
         os: [macos-latest, windows-latest, ubuntu-latest]
-        cmake: ['3.10.x', '3.29.x'] # Older version (Ubuntu 18.04) and newest
-        exclude:
-          - os: windows-latest
-            cmake: '3.10.x'
-          - os: macos-latest # Skip the old cmake on latest macos - doesn't handle ARM64 aarch correctly
-            cmake: '3.10.x'
+        cmake: ['3.22.x', '4.0.x']
 
     steps:
-    - name: Cache .hunter folder
-      if: matrix.os != 'windows-latest'
-      uses: actions/cache@v4
-      with:
-        path: ~/.hunter/
-        key: hunter-${{ matrix.os }}-${{ matrix.cmake }}
-    - name: Cache .hunter folder
-      if: matrix.os == 'windows-latest'
-      uses: actions/cache@v4
-      with:
-        path: C:/.hunter/
-        key: hunter-${{ matrix.os }}-${{ matrix.cmake }}
-
     - uses: actions/checkout@v4
       with:
         submodules: 'recursive'
@@ -102,7 +114,7 @@ jobs:
       if: matrix.os == 'ubuntu-latest'
       run: |
         sudo apt-get update
-        sudo apt-get install libopencv-dev
+        sudo apt-get install libopencv-dev libudev-dev libusb-1.0-0-dev
 
     - name: Install dependencies
       if: matrix.os == 'windows-latest'
@@ -110,56 +122,33 @@ jobs:
         choco install opencv
         echo "OpenCV_DIR=C:\tools\opencv\build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
 
-    - name: Build (old CMake, gcc/Clang)
-      if: matrix.cmake == '3.10.x' && matrix.os != 'windows-latest'
+    - name: Build
       run: |
-        cmake -H. -Bbuild -D'CMAKE_BUILD_TYPE=Release' -D'HUNTER_CONFIGURATION_TYPES=Release' -D'DEPTHAI_BUILD_EXAMPLES=ON' -D'DEPTHAI_BUILD_TESTS=ON' ${{ env.CMAKE_ARGS }}
-        cmake --build build --config Release -- -j4
-
-    # CMake binaries unavailable
-    # - name: Build (old CMake, MSVC)
-    #   if: matrix.cmake == '3.10.x' && matrix.os == 'windows-latest'
-    #   run: |
-    #     cmake -H. -Bbuild -D'DEPTHAI_BUILD_EXAMPLES=ON' -D'DEPTHAI_BUILD_TESTS=ON'
-    #     cmake --build build
-
-    - name: Build (newest CMake)
-      if: matrix.cmake != '3.10.x'
-      run: |
-        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D HUNTER_CONFIGURATION_TYPES=Release -D DEPTHAI_BUILD_EXAMPLES=ON -D DEPTHAI_BUILD_TESTS=ON ${{ env.CMAKE_ARGS }}
+        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D DEPTHAI_BUILD_EXAMPLES=ON -D DEPTHAI_BUILD_TESTS=ON ${{ env.CMAKE_ARGS }}
         cmake --build build --parallel 4 --config Release
 
   integration:
     runs-on: ${{ matrix.os }}
+    needs: [precheck]
+    if: needs.precheck.outputs.should_run == 'true'
     strategy:
       matrix:
         os: [macos-latest, windows-latest, ubuntu-latest]
         build-type: [Debug, Release]
-        shared: [true, false]
+        # shared: [true, false]
+        shared: [true]
         platform: [x64]
-        include:
-          - platform: Win32
-            os: windows-latest
-            shared: true
-            build-type: Debug
-          - platform: Win32
-            os: windows-latest
-            shared: true
-            build-type: Release
+        # TODO(Morato) - add back Win32 and shared builds to CI
+        # include:
+        #   - platform: Win32
+        #     os: windows-latest
+        #     shared: true
+        #     build-type: Debug
+        #   - platform: Win32
+        #     os: windows-latest
+        #     shared: true
+        #     build-type: Release
     steps:
-    - name: Cache .hunter folder
-      if: matrix.os != 'windows-latest'
-      uses: actions/cache@v4
-      with:
-        path: ~/.hunter/
-        key: hunter-${{ matrix.os }}-shared_${{ matrix.shared }}
-    - name: Cache .hunter folder
-      if: matrix.os == 'windows-latest'
-      uses: actions/cache@v4
-      with:
-        path: C:/.hunter/
-        key: hunter-${{ matrix.os }}-shared_${{ matrix.shared }}
-
     - uses: actions/checkout@v4
       with:
         submodules: 'recursive'
@@ -173,7 +162,7 @@ jobs:
       if: matrix.os == 'ubuntu-latest'
       run: |
         sudo apt-get update
-        sudo apt-get install libopencv-dev
+        sudo apt-get install libopencv-dev libudev-dev libusb-1.0-0-dev
 
     - name: Install dependencies
       if: matrix.os == 'windows-latest'
@@ -204,34 +193,34 @@ jobs:
       with:
         name: windows-prebuilt-win64-${{ matrix.build-type }}
         path: ${{ env.GITHUB_WORKSPACE }}/depthai_install/
+    # TODO(Morato) - add back Win32 and shared builds to CI
+    # - name: Upload Win32 shared library
+    #   if: matrix.os == 'windows-latest' && matrix.shared && matrix.platform == 'Win32'
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: windows-prebuilt-win32-no-opencv-${{ matrix.build-type }}
+    #     path: ${{ env.GITHUB_WORKSPACE }}/depthai_install/
 
-    - name: Upload Win32 shared library
-      if: matrix.os == 'windows-latest' && matrix.shared && matrix.platform == 'Win32'
-      uses: actions/upload-artifact@v4
-      with:
-        name: windows-prebuilt-win32-no-opencv-${{ matrix.build-type }}
-        path: ${{ env.GITHUB_WORKSPACE }}/depthai_install/
-
-    - name: Build and test add_subdirectory
-      run: |
-        cmake -S tests/integration/ -B tests/integration/build_add_subdirectory -D TEST_FIND_PACKAGE=OFF ${{ env.CMAKE_ARGS }}
-        cmake --build tests/integration/build_add_subdirectory --config ${{ matrix.build-type }} --parallel 4
-        cd tests/integration/build_add_subdirectory
-        ctest -C ${{ matrix.build-type }} --output-on-failure --no-tests=error
+    # - name: Build and test add_subdirectory
+    #   run: |
+    #     cmake -S tests/integration/ -B tests/integration/build_add_subdirectory -D TEST_FIND_PACKAGE=OFF ${{ env.CMAKE_ARGS }}
+    #     cmake --build tests/integration/build_add_subdirectory --config ${{ matrix.build-type }} --parallel 4
+    #     cd tests/integration/build_add_subdirectory
+    #     ctest -C ${{ matrix.build-type }} --output-on-failure --no-tests=error
 
     - name: Build and test find_package (installed)
       run: |
-        cmake -S tests/integration/ -B tests/integration/build_find_package -D TEST_FIND_PACKAGE=ON -D depthai_DIR=$GITHUB_WORKSPACE/depthai_install/lib/cmake/depthai ${{ env.CMAKE_ARGS }}
+        cmake -S tests/integration/ -B tests/integration/build_find_package -D TEST_FIND_PACKAGE=ON -D CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/depthai_install/ ${{ env.CMAKE_ARGS }}
         cmake --build tests/integration/build_find_package --config ${{ matrix.build-type }} --parallel 4
         cd tests/integration/build_find_package
         ctest -C ${{ matrix.build-type }} --output-on-failure --no-tests=error
 
-    - name: Build and test find_package (build directory)
-      run: |
-        cmake -S tests/integration/ -B tests/integration/build_find_package_2 -D TEST_FIND_PACKAGE=ON -D depthai_DIR=$GITHUB_WORKSPACE/build ${{ env.CMAKE_ARGS }}
-        cmake --build tests/integration/build_find_package_2 --config ${{ matrix.build-type }} --parallel 4
-        cd tests/integration/build_find_package_2
-        ctest -C ${{ matrix.build-type }} --output-on-failure --no-tests=error
+    # - name: Build and test find_package (build directory)
+    #   run: |
+    #     cmake -S tests/integration/ -B tests/integration/build_find_package_2 -D TEST_FIND_PACKAGE=ON -D depthai_DIR=$GITHUB_WORKSPACE/build ${{ env.CMAKE_ARGS }}
+    #     cmake --build tests/integration/build_find_package_2 --config ${{ matrix.build-type }} --parallel 4
+    #     cd tests/integration/build_find_package_2
+    #     ctest -C ${{ matrix.build-type }} --output-on-failure --no-tests=error
 
 
   release:
@@ -268,19 +257,19 @@ jobs:
         merge-multiple: true
         path: depthai-core-${{ steps.tag.outputs.version }}-win64
 
-    - name: Download Win32 artifacts
-      uses: actions/download-artifact@v4
-      with:
-        pattern: windows-prebuilt-win32-no-opencv*
-        merge-multiple: true
-        path: depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv
+    # - name: Download Win32 artifacts
+    #   uses: actions/download-artifact@v4
+    #   with:
+    #     pattern: windows-prebuilt-win32-no-opencv*
+    #     merge-multiple: true
+    #     path: depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv
 
     - name: Create release assets
       run: |
         git-archive-all depthai-core-${{ steps.tag.outputs.version }}.tar.gz
         git-archive-all depthai-core-${{ steps.tag.outputs.version }}.zip
         zip -r depthai-core-${{ steps.tag.outputs.version }}-win64.zip depthai-core-${{ steps.tag.outputs.version }}-win64
-        zip -r depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv
+        # zip -r depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv
 
     # Create GitHub release
     - uses: actions/create-release@master
@@ -331,12 +320,12 @@ jobs:
         asset_name: depthai-core-${{ steps.tag.outputs.version }}-win64.zip
         asset_content_type: application/octet-stream
 
-    - name: Upload Win32 package (zip)
-      uses: actions/upload-release-asset@v1.0.1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.createRelease.outputs.upload_url }}
-        asset_path: ${{ github.workspace }}/depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip
-        asset_name: depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip
-        asset_content_type: application/octet-stream
+    # - name: Upload Win32 package (zip)
+    #   uses: actions/upload-release-asset@v1.0.1
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   with:
+    #     upload_url: ${{ steps.createRelease.outputs.upload_url }}
+    #     asset_path: ${{ github.workspace }}/depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip
+    #     asset_name: depthai-core-${{ steps.tag.outputs.version }}-win32-no-opencv.zip
+    #     asset_content_type: application/octet-stream
