check pkgconfig

diff --git a/.github/workflows/python-main.yml b/.github/workflows/python-main.yml
--- a/.github/workflows/python-main.yml
+++ b/.github/workflows/python-main.yml
@@ -511,6 +511,11 @@ jobs:
           cd bindings/python
           /opt/python/cp38-cp38/bin/python3.8 -m pip install cmake
           ln -s /opt/python/cp38-cp38/bin/cmake /bin/
+      - name: Check pkgconfig for XCB, X11 and Wayland
+        run: |
+          pkg-config --exists xcb && echo "xcb found" || echo "xcb missing"
+          pkg-config --exists x11 && echo "x11 found" || echo "x11 missing"
+          pkg-config --exists wayland-client && echo "wayland-client found" || echo "wayland-client missing"
       - name: Setup ninja required for arm64 builds
         run: |
           git clone https://github.com/ninja-build/ninja.git
